#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_annonce_deletefront:
    path: '/annoncefront/{id}/delete'
    controller: 'App\Controller\AnnonceFrontController::delete'